{% set version = "0.2.6" %}

package:
  name: dataspyre
  version: {{ version }}

source:
  fn: DataSpyre.tar.gz
  url: https://pypi.io/packages/source/D/DataSpyre/DataSpyre-{{ version }}.tar.gz
  sha256: 7a7cf1f355f237d66c678cadc96b2de7cf1258fd065fcc6154189bc9de96266a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - cherrypy
    - jinja2
    - matplotlib

test:
  imports:
    - spyre

about:
  home: https://github.com/adamhajari/spyre
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Web Application Framework for simple user interface.'

extra:
  recipe-maintainers:
    - ocefpaf
