travis:
  secure:
    BINSTAR_TOKEN: lxYE0QdcyElvaOe8eNnlMTIoCe5d9psimEUlo4R4G0/xREA1TaI4BgtHblN50HQMvin9iIesVdqSfzoo/hcDpduc/JX8eiPq46UGKYVIIu785L9dsebaBEXeT/BojImp6Cqvn81saOWjoiYvFLUK7HNcGxO0s4Aas7kSQcBMdepj3Vxjv4AZV9v5Zcprs02NECX08Rhnx9iJ+Jo1yGs0uAMCZkRoT5iEyeGX76joV/FGKNBpIwqZxcEB8D6hBm06lhrDSByJur1/bEwUN67mHHEWN6J6LGBw6ro56vLpb++ZjmfQDLhPypzwVCi+CogchELrBE2KlteWOMtkfk0aBjhKh4xzYkdmngzMJkeCDg2VCa66HJ9kgBcUAo0ier3182y/z8qbQxGnmRk9Le20nkPk1/41dBSdapPsKeZOC51jsT0347HcOQpYHbT9xSLxsBl1jP+q3Eoqcgd0IE851F7RPKS61PujX55G0ySIlTja49+ApkDxWzQo2GrySnJkbmYXXFlq7MIYf5Yg5EXKaO31sFgbPcA4YWimmsBI3Oj7nHzuZmzwN8ceJonCXzTL927RisHkY4UD8+oadIU+yUcCs8WZHUs3jpevPV1G1boiP/9StCn3DslIw32WaXMx4eXKxGhFThaaZv90MsceCi4zugnyWH/rNZxpTmBkY4o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
