travis:
  secure:
    BINSTAR_TOKEN: bGPpvmdd3f8lV2Ld2vCzHjKFEA0iqXi1e02/4iUcWtSzQ4HdhvsoZ8u/AX03rxv7SNhP1zCq5ydssqYImnt1QTQd1aiIAJrqpZubVAx1OACrLdMFrevuON2cKjaMjJJroSAQCbHY0lSnB2/CqqjO/W/ekPNsnePLWjXkMplP4BpL0LlemiqCBRNgdQLP27WVvl9Qn982IrCKYh5HefWHl4TOo2pUAQ34JosBtDIep+inRbLKt2on4YBg3F5fw+2vAYs/pWuorgPXGParKgnMnhuGAg5dzL4hEWtscsRa4otu47zI7atXg9Pa9rEfCqCn7qmjqJz2ecVfQL1NCXjxXWDvO9cCcU4l4f+5SwcO7XQRALqXQDLGR/7O+kWvPv9LbNiAaxH1cp6NEcERW8D7Pp8kD0qhvZcY0DPv3bEOWBvMMR6cjcR8/Xj1WmzoVu2hZ3CZjFPVAZPETzZSC/AKGoXakJvQJO0qAKp7fPYwQpjvn1LRnXLqNmdTAq7XwCFE6H+gzEzpM2EpQuZqa37BMNjXTshBzu30HH393FIfbzjcwFBs7hDfkM4i3+zjpCDCm+wJULgYMAVd/BfZw/sY2YR/ZAn/GJczfWzOxyrcS+ROfBa/IccIdu47D2hhez3eitG0395+5c5ALz7lodeOo/EZfFyH0N5Hb75a53U3j08=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
